#!/bin/bash
#SBATCH --job-name=combine
#SBATCH --partition=normal
#SBATCH --time=06:00:00
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem=8G
#SBATCH --output=/home/l/l_alth03/logs/combine-%j.out
#SBATCH --error=/home/l/l_alth03/logs/combine-%j.err

# sbatch /cloud/wwu1/p_agweinheimer/AGW_LowRad/home/l_alth03/simulations/HermeticTPC/combine.sub

LOGSDIR="/home/l/l_alth03/logs"
mkdir -p $LOGSDIR

# Provide a container path to the singularity image with Geant4
CONTAINER_PATH="/cloud/wwu1/p_agweinheimer/AGW_LowRad/software/container/xenonnt_mc_ms_20260112.sif"
CONTAINER_BIND="--bind /cloud/wwu1/p_agweinheimer/AGW_LowRad:/cloud/wwu1/p_agweinheimer/AGW_LowRad --bind /scratch/tmp/$USER:/scratch/tmp/$USER"

ml Singularity

echo "Combining fuse output files..."
singularity exec $CONTAINER_BIND $CONTAINER_PATH /bin/bash -c "python /cloud/wwu1/p_agweinheimer/AGW_LowRad/home/l_alth03/simulations/HermeticTPC/combine_fuse_output.py --config_file /cloud/wwu1/p_agweinheimer/AGW_LowRad/home/l_alth03/simulations/software/20251205_HermeticTPC/analysis/fuse_files/XENONnT_public_config.json -o /scratch/tmp/l_alth03/20251205_HermeticTPC/combined_fuse_output.h5 -i /scratch/tmp/l_alth03/20251205_HermeticTPC/fuse_data"

echo "Combining parquet output files..."
singularity exec $CONTAINER_BIND $CONTAINER_PATH /bin/bash -c "python /cloud/wwu1/p_agweinheimer/AGW_LowRad/home/l_alth03/simulations/HermeticTPC/combine_parquet_output.py -o /scratch/tmp/l_alth03/20251205_HermeticTPC/combined_parquet_output.h5 -i /scratch/tmp/l_alth03/20251205_HermeticTPC/parquet"
