################
#VERBOSITY
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/xe/gun/verbose 0

##################
# isotropic emission
/xe/gun/angtype iso

# make sure the volume below is a bit larger than the object the source will be confined to
/xe/gun/type   Volume
/xe/gun/shape  Cylinder
/xe/gun/center 0. 0. 0. cm
/xe/gun/radius 250 cm
/xe/gun/halfz  250 cm

##################
# Select the volume to confine the source. 
/xe/gun/confine phys_GXeSapphireTub phys_GXeSapphireCap phys_LXeSapphireTub phys_LXeSapphireCap

##################
# particle type + energy spectrum
/xe/gun/energytype Spectrum
/xe/gun/energyspectrum ./macros/spectra/neutron_Al2O3_Th232.dat
/xe/gun/particle neutron

# postpone decay
#/xe/Postponedecay false
#/xe/MaxLifeTime 1000000 ns

##################
# Tree Filling options
#/run/writeEmpty false
